// 내글 조회 
export const FETCH_DIARIES_REQUEST = 'FETCH_DIARIES_REQUEST';
export const FETCH_DIARIES_SUCCESS = 'FETCH_DIARIES_SUCCESS';
export const FETCH_DIARIES_FAILURE = 'FETCH_DIARIES_FAILURE';


// 감정만 저장하는 emotionOnly
export const SAVE_EMOTION_ONLY_REQUEST = 'SAVE_EMOTION_ONLY_REQUEST';
export const SAVE_EMOTION_ONLY_SUCCESS = 'SAVE_EMOTION_ONLY_SUCCESS';
export const SAVE_EMOTION_ONLY_FAILURE = 'SAVE_EMOTION_ONLY_FAILURE';