// 내글 조회
export const FETCH_DIARIES_REQUEST = 'FETCH_DIARIES_REQUEST';
export const FETCH_DIARIES_SUCCESS = 'FETCH_DIARIES_SUCCESS';
export const FETCH_DIARIES_FAILURE = 'FETCH_DIARIES_FAILURE';

// 감정만 저장
export const SAVE_EMOTION_ONLY_REQUEST = 'SAVE_EMOTION_ONLY_REQUEST';
export const SAVE_EMOTION_ONLY_SUCCESS = 'SAVE_EMOTION_ONLY_SUCCESS';
export const SAVE_EMOTION_ONLY_FAILURE = 'SAVE_EMOTION_ONLY_FAILURE';

// 수정
export const FETCH_DIARY_DETAIL_REQUEST = 'FETCH_DIARY_DETAIL_REQUEST';
export const FETCH_DIARY_DETAIL_SUCCESS = 'FETCH_DIARY_DETAIL_SUCCESS';
export const FETCH_DIARY_DETAIL_FAILURE = 'FETCH_DIARY_DETAIL_FAILURE';

// 수정 저장
export const UPDATE_DIARY_REQUEST = 'UPDATE_DIARY_REQUEST';
export const UPDATE_DIARY_SUCCESS = 'UPDATE_DIARY_SUCCESS';
export const UPDATE_DIARY_FAILURE = 'UPDATE_DIARY_FAILURE';
export const RESET_UPDATE_STATUS = 'RESET_UPDATE_STATUS';


// 팔로우한 일기 
export const FOLLOWER_DIARY_REQUEST = 'FOLLOWER_DIARY_REQUEST';
export const FOLLOWER_DIARY_SUCCESS = 'FOLLOWER_DIARY_SUCCESS';
export const FOLLOWER_DIARY_FAILURE = 'FOLLOWER_DIARY_FAILURE';

// 일기 삭제 
export const DELETE_DIARY_REQUEST = "DELETE_DIARY_REQUEST";
export const DELETE_DIARY_SUCCESS = "DELETE_DIARY_REQUEST";
export const DELETE_DIARY_FAILURE = "DELETE_DIARY_REQUEST";


// 마이페이지에서 남일기 공개된거.
export const FETCH_PUBLIC_DIARIES_REQUEST = 'FETCH_PUBLIC_DIARIES_REQUEST';
export const FETCH_PUBLIC_DIARIES_SUCCESS = 'FETCH_PUBLIC_DIARIES_SUCCESS';
export const FETCH_PUBLIC_DIARIES_FAILURE = 'FETCH_PUBLIC_DIARIES_FAILURE';